### Numpy Installation

In [23]:
#pip install numpy

### Import Numpy

In [70]:
import numpy as np

### Basics

In [71]:
a = np.array([1,2,3],dtype='int8')
print(a)

[1 2 3]


In [72]:
b = np.array([[9.0,8.0,7.0],[5.0,6.0,7.0]])
print(b)

[[9. 8. 7.]
 [5. 6. 7.]]


In [73]:
#Get Dimension
print(a.ndim)
print(b.ndim)

1
2


In [74]:
#Get Shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [75]:
#Get Type
print(a.dtype)
z = np.array([1,2,3], dtype='int16')
print(z.dtype)

int8
int16


In [76]:
# Length
print(a.size)
print(b.size)

3
6


### Accessing Elements

In [77]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [78]:
#Specific Element
print(a[0,1])
print(a[0,-1])

2
7


In [79]:
# Get a specific row
print(a[0,:])
print(a[1,:])

[1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14]


In [80]:
# Get a specific col
print(a[:,0])
print(a[:,1])

[1 8]
[2 9]


In [83]:
# [2,4,6] [startindex:endindex:step]
print(a[:,1:-1:2])

[[20  4 89]
 [ 9 11 98]]


In [84]:
a

array([[  1,  20,   3,   4,   5,  89, 999],
       [  8,   9,  10,  11,  12,  98, 999]])

In [89]:
#Element Modification

a[0,1] = 20
print(a)

a[:,-1] = 999
print(a)

a[:,-2] = [89,98]
print(a)

#a[:,:] = [8888,7777,6666]
#print(a)

a[:,:] = [99,90]
print(a)

[[99 20 99 99 99 99 99]
 [99 99 99 99 99 99 99]]
[[ 99  20  99  99  99  99 999]
 [ 99  99  99  99  99  99 999]]
[[ 99  20  99  99  99  89 999]
 [ 99  99  99  99  99  98 999]]


ValueError: could not broadcast input array from shape (2,) into shape (2,7)

### Reshape

In [51]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(3,4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### 3D

In [52]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [53]:
# Get specific element
print(b[0,1,1])

4


In [55]:
print(b[0,0,1])

2


### Different Types of Arrays

#### All 0s

In [56]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

#### All 1s

In [57]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

#### Different Number

In [58]:
np.full((2,2),88)

array([[88, 88],
       [88, 88]])

#### Random Matrix

In [59]:
np.random.randint(10,99,size=(2,2))

array([[74, 34],
       [66, 49]])

#### Identity Matrix

In [60]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Copying Arrays

In [61]:
a = np.array([1,2,3])
print(a)
b=a
b[0] = 100
print(a)

[1 2 3]
[100   2   3]


In [62]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


### Mathematical Operations

In [63]:
a = np.array([1,2,3,4,5])
print(a)

a=a+2
print(a)

[1 2 3 4 5]
[3 4 5 6 7]


In [64]:
b=np.array([1,2,3,4,5])
b=a+b
print(b)

[ 4  6  8 10 12]


#### Matrix Multiplication

In [65]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),4)
print(b)

print(np.matmul(a,b))

[[1. 1. 1.]
 [1. 1. 1.]]
[[4 4]
 [4 4]
 [4 4]]
[[12. 12.]
 [12. 12.]]


#### Statistics

In [66]:
a = np.array([[1,2,3],[4,5,6]])

print(np.min(a,axis=0)) #Column
print(np.min(a,axis=1)) #row

[1 2 3]
[1 4]


In [68]:
min(a[0])

1